version: '3.3'

services:
  db:
    image: mysql:oracle
    ports:
      - "3307:3006"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=fitlaunch
  findacoach:
    image: dido/findacoach:v1
    depends_on: [db]
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root

