version: '3.8'

services:
  api:
    image: dido/api:v1
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - db-network
  db:
    image: mysql:oracle
    container_name: db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fitlaunch
    restart: on-failure
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
